#!/bin/bash

source versions

for f in dataflow-errorprone-${DATAFLOW_VERSION}.jar error_prone_core-${EP_VERSION}-with-dependencies.jar; do
  [[ -f $f ]] || { echo "ERROR: missing $f"; exit 1; }
done
echo "All pre-requisites OK"

